language: python

env:
  global:
    CIBW_BUILD_VERBOSITY: 3
    PIP: pip3

language: generic

os:
  - linux
  - osx

matrix:
  exclude:
    - os: linux

script:
  - export CXXFLAGS="-std=c++11"
  - $PIP install pip setuptools -U
  - $PIP install cibuildwheel==0.10.0
  - eval "buildwheel() { cibuildwheel --output-dir wheelhouse >>buildwheel.log 2>&1; }"
  - travis_wait 60 buildwheel || (tail -c 3670016 buildwheel.log && exit 1)
  - tail -c 3670016 buildwheel.log
  - ls wheelhouse
  - $PIP install awscli --upgrade
  - python3 -m awscli s3 sync ./wheelhouse/ s3://supersqlite.plasticity.ai/wheelhouse/
